### ISSUE TITLE
Clear-text logging of sensitive information

### ISSUE THREAD

**Issue by paudelgaurav** [WesionaryTEAM/go_clean_architecture#110]
Tracking issue for:
- [ ] https://github.com/wesionaryTEAM/go_clean_architecture/security/code-scanning/1

CWE:
- https://cwe.mitre.org/data/definitions/312.html
- https://cwe.mitre.org/data/definitions/315.html
- https://cwe.mitre.org/data/definitions/359.html

**Comment by palvaibhav** [comment]
Hi, I would like to work on this issue but the link seems to be broken.

**Comment by paudelgaurav** [comment]
@palvaibhav For now, the link is only accessible to internal team.
You can use this picture as reference for above issue.
![Screenshot 2024-06-06 at 16 11 36](https://github.com/wesionaryTEAM/go_clean_architecture/assets/79510196/873f5669-3239-4382-a647-3dd84b3f78d3)
